### ISSUE TITLE
NPM package or send data to a target API / website

### ISSUE THREAD

**Issue by eyal282** [fitztrev/rosen-score#3]
Hello! I am the creator of Chess ELO Role, and I have grown interested in the rosen score. I want to be able to use it as an NPM package for Node.js Could you add it so I can count how many rosen trophies an individual got, and how much unique trophies he got vs the max trophies? My plan is to attach your website for more details.

My bot also already has OAuth2 for linking your account to prove you own it, so the relation is really nice.

If you edited your website to allow a user to add a target website to launch the data to, that would also be okay, but allow me to pre-write it with something like https://github.com/fitztrev/rosen-score/blob/main/package.json#L9 where L9 is a parameter, so the user isn't forced to write my website

https://github.com/eyal282/Chess-ELO-Discord-Bot

Edit: it seems that the second solution would not only allow users to fake their score, but also others score by sending a fake API.

**Comment by eyal282** [comment]
Also where is my achievement for pawn diamond?
https://lichess.org/2yFy2EZc/white#27

**Comment by fitztrev** [comment]
Not planning on making it an npm package right now.

Pawn diamonds can't start on the 2nd rank.
