### ISSUE TITLE
Fetching EricRosens games every time 

### ISSUE THREAD

**Issue by ReubenMenezes** [fitztrev/rosen-score#5]
Heya, when you click on the "click here to see Eric Rosen's", it always fetches the games. Isn't it easier to make an html page with his trophies instead of wasting so much time?

**Comment by fitztrev** [comment]
Hi, there is a cache that keeps track of his games that match against the trophies. So it doesn't have to re-download from the Lichess API.

I don't want to maintain an HTML page as a cache but maybe there's some other way. I'll keep it as an idea for future development. Thanks.
